spring.application.name=estoque-api

## Database Config
spring.datasource.url=jdbc:h2:mem:devdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


## JPA Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## H2 Config
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## Jackson Config
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

## Amazon S3
aws.bucket.name=stock-managerment-project
aws.region=us-east-1
aws.bucket.directory=catalog
aws.secret.key=${AWS_SECRET_ACCESS_KEY}
aws.access.key=${AWS_ACCESS_KEY_ID}

